"use strict";

const properties = [
    {
        id: 1,
        slug: "scire-connect",
        name: "Scire Connect",
        developer: "Scire Empreendimentos",
        city: "São José",
        neighborhood: "Barreiros",
        state: "SC",
        address: null,
        coordinates: null,
        propertyTypes: ["Apartamento", "Studio"],
        bedrooms: [1, 2],
        suites: [1],
        areaMin: 32,
        areaMax: 57,
        parking: null,
        price: null,
        paymentInfo: null,
        delivery: null,
        headline: "Conecte-se com uma vida completa!",
        shortDescription: "Studios e apartamentos de 1 ou 2 dormitórios com opção de suíte, projetados especialmente para proporcionar o máximo de conforto e praticidade.",
        description: "O Scire Connect está estrategicamente localizado em Barreiros, uma das regiões mais dinâmicas e promissoras da Grande Florianópolis. Com acesso fácil a diversas conveniências, a poucos minutos do Shopping Itaguaçu e às principais vias de acesso da cidade.",
        highlights: [
            "Localização Estratégica",
            "Infraestrutura Completa",
            "Rooftop com Hidromassagem",
            "Portaria Remota"
        ],
        amenities: [
            "Rooftop",
            "Hidromassagem",
            "Fireplace",
            "Salão de Festas",
            "Academia",
            "Coworking",
            "Espaço Pizza/Parrila",
            "Cinema",
            "Sala de Jogos",
            "Pet Place",
            "Horta",
            "Playground",
            "Honest Market",
            "Ponto de Recarga VE",
            "Espaço Delivery",
            "Lavanderia OMO"
        ],
        nearby: [
            "Hospital Unimed: 1,1 km",
            "Shopping Itaguaçu: 1,3 km",
            "Fort Atacadista: 1,5 km",
            "UPA Continente: 2,2 km"
        ],
        typologies: [
            "Studio (32m²)",
            "1 dormitório (33m²)",
            "2 dormitórios (50m²)",
            "2 dormitórios com suíte (52m² a 57m²)"
        ],
        coverImage: "assets/images/properties/scire-connect/cover.webp?v=2",
        logo: null,
        gallery: [],
        legalDisclaimer: "O presente material tem caráter exclusivamente informativo e as imagens são meramente ilustrativas."
    },
    {
        id: 2,
        slug: "scire-view",
        name: "Scire View",
        developer: "Scire Empreendimentos",
        city: "São José",
        neighborhood: "Centro Histórico",
        state: "SC",
        address: "Rua Coletor Irineu Comelli",
        coordinates: null,
        propertyTypes: ["Apartamento", "Studio"],
        bedrooms: [2, 3],
        suites: [1],
        areaMin: 32,
        areaMax: 67,
        parking: null,
        price: null,
        paymentInfo: null,
        delivery: null,
        headline: "Seu novo jeito de ver e viver São José.",
        shortDescription: "Studios e apartamentos de 2 ou 3 dormitórios, com opções de suíte, pensados para quem valoriza conforto, bem-estar e um estilo de vida mais leve.",
        description: "Com uma localização privilegiada e apartamentos com uma vista deslumbrante para o mar, o Scire View oferece uma experiência única, onde arquitetura, paisagem e qualidade de vida se encontram em perfeita harmonia.",
        highlights: [
            "Vista para o mar",
            "Arquitetura Contemporânea",
            "Plantas Inteligentes",
            "Localização Privilegiada"
        ],
        amenities: [
            "Playground",
            "Pet Place",
            "Coworking",
            "Fire Place",
            "Brinquedoteca",
            "Academia",
            "Redário",
            "Espaço Delivery",
            "Piscina Adulto e Infantil",
            "Salão Gourmet",
            "Área de Jogos Externa",
            "Salão de Festas",
            "Área de Estar",
            "Quadra de Areia",
            "Área de Piquenique",
            "Quiosque Gourmet",
            "Horta Comunitária",
            "Fitness Externo",
            "Portaria"
        ],
        nearby: [
            "Mini Mercado Bom Vizinho: 290m",
            "Farmácia São José: 620m",
            "Câmara Municipal de São José: 1,3 km",
            "Continente Shopping: 3,6 km"
        ],
        typologies: [
            "Studio (32m² a 33m²)",
            "2 dormitórios (52m²)",
            "2 dormitórios com suíte (54m² a 55m²)",
            "3 dormitórios com suíte (67m²)"
        ],
        coverImage: "assets/images/properties/scire-view/cover.webp?v=2",
        logo: null,
        gallery: [],
        legalDisclaimer: "Material exclusivamente informativo. Imagens meramente ilustrativas."
    },
    {
        id: 3,
        slug: "scire-botanic",
        name: "Scire Botanic",
        developer: "Scire Empreendimentos",
        city: "São José",
        neighborhood: "Areias",
        state: "SC",
        address: "Rua Álvaro Medeiros de Santiago, 1630",
        coordinates: null,
        propertyTypes: ["Apartamento"],
        bedrooms: [2],
        suites: [1],
        areaMin: 47,
        areaMax: 57,
        parking: null,
        price: null,
        paymentInfo: null,
        delivery: null,
        headline: "Onde a natureza encontra o seu lar",
        shortDescription: "A proximidade com a natureza se une ao conforto de um apartamento moderno. Uma vida completa está ao seu alcance.",
        description: "No Scire Botanic, em Areias, São José, uma vida completa está ao seu alcance. A proximidade com a natureza se une ao conforto de um apartamento moderno, proporcionando a praticidade e a tranquilidade que você sempre sonhou.",
        highlights: [
            "Bosque com pista de caminhada",
            "Plantas inteligentes",
            "Fácil acesso às principais vias"
        ],
        amenities: [
            "Salão de Festas",
            "Playground",
            "Quiosques Grill",
            "Salão de Jogos",
            "Piscina",
            "Coworking",
            "Espaço Fitness",
            "Sala de Reuniões",
            "Honest Market",
            "Pet Place + Pet Care",
            "Espaço Gourmet",
            "Bosque com Pista de Caminhada",
            "Gourmet Pub",
            "Fire Place",
            "Horta",
            "Quadra",
            "Redário",
            "Fitness Externo"
        ],
        nearby: [
            "Giassi Supermercados: 1,0 km",
            "BR-101: 1,2 km",
            "Fort Atacadista: 1,6 km",
            "Shopping Itaguaçu: 6,0 km"
        ],
        typologies: [
            "2 dormitórios (47m² a 48m²)",
            "2 dormitórios demi-suítes (53m²)",
            "1 suíte + 1 dormitório (53m² a 57m²)"
        ],
        coverImage: "assets/images/properties/scire-botanic/cover.webp?v=2",
        logo: null,
        gallery: [],
        legalDisclaimer: null
    },
    {
        id: 4,
        slug: "scire-boulevard",
        name: "Scire Boulevard",
        developer: "Scire Empreendimentos",
        city: "Palhoça",
        neighborhood: "Passa Vinte",
        state: "SC",
        address: "R. Ver. Jacob Knabben da Silva",
        coordinates: null,
        propertyTypes: ["Apartamento"],
        bedrooms: [2],
        suites: [1],
        areaMin: 47,
        areaMax: 57,
        parking: null,
        price: null,
        paymentInfo: null,
        delivery: null,
        headline: "Um projeto inspirado pela qualidade de vida.",
        shortDescription: "O Scire Boulevard une a arquitetura contemporânea a uma infraestrutura de lazer e conveniência com lojas no próprio empreendimento.",
        description: "Localizado em Palhoça, ao lado do portal da Pedra Branca, o Scire Boulevard foi projetado para unir as facilidades de uma região em pleno desenvolvimento a um empreendimento que valoriza o seu conforto. Conta com um boulevard de lojas no acesso principal.",
        highlights: [
            "Boulevard com 10 lojas no acesso",
            "Área verde preservada",
            "Projeto assinado por Methafora Arquitetos"
        ],
        amenities: [
            "Salão de Festas",
            "Playground",
            "Sala de Jogos",
            "Piscina",
            "Brinquedoteca",
            "Academia",
            "Coworking / Sala de Reuniões",
            "Fireplace",
            "Pet Place + Pet Care",
            "Espaço Gourmet",
            "Cinema",
            "Horta",
            "Espaço Zen",
            "Redário",
            "Sala de Ferramentas",
            "Espaço Delivery / Honest Market",
            "Quiosques Grill",
            "Recarga de Veículos Elétricos"
        ],
        nearby: [
            "Shopping Via Catarina: 1,8 km",
            "UNISUL Pedra Branca: 2,4 km",
            "IFSC Campus Palhoça: 1 km",
            "Centro de Palhoça: 4,9 km"
        ],
        typologies: [
            "2 dormitórios (47m² a 48m²)",
            "2 dormitórios demi-suítes (53m²)",
            "1 suíte + 1 dormitório (53m² a 57m²)"
        ],
        coverImage: "assets/images/properties/scire-boulevard/cover.webp?v=2",
        logo: null,
        gallery: [],
        legalDisclaimer: "Matrícula registrada sob n.º 66.428, no Ofício de Registro de Imóveis."
    },
    {
        id: 5,
        slug: "terra-golden-resort",
        name: "Terrá Golden Resort",
        developer: "Paysage Corpal",
        city: "São José",
        neighborhood: "Terrá",
        state: "SC",
        address: "Rua Kiliano Hames, 1049",
        coordinates: null,
        propertyTypes: ["Terreno"],
        bedrooms: [],
        suites: [],
        areaMin: null,
        areaMax: null,
        parking: null,
        price: null,
        paymentInfo: null,
        delivery: null,
        headline: "O primeiro Condomínio Resort de terrenos.",
        shortDescription: "Eleve a sua vida no novo condomínio resort de terrenos do bairro Terrá, com acesso fácil à Ilha de Florianópolis.",
        description: "Mais que um bairro, o Terrá é a primeira urbanicidade viva de São José e Grande Florianópolis. O Terrá Golden Resort é arquitetado para proporcionar os melhores momentos, com áreas de convívio e lazer integradas.",
        highlights: [
            "Condomínio Fechado de Lotes",
            "Infraestrutura Premium de Resort",
            "Acesso fácil à BR-101"
        ],
        amenities: [
            "Piscina Adulto e Infantil",
            "Splash Kids",
            "Fitness Interno e Externo",
            "Área Beach (Quadra de Areia)",
            "Quadra Esportiva",
            "Salão de Festas & Coworking",
            "Espaço Kids Integrado",
            "Quadras de Beach Tennis"
        ],
        nearby: [],
        typologies: [],
        coverImage: "assets/images/properties/terra-golden-resort/cover.webp?v=2",
        logo: null,
        gallery: [],
        legalDisclaimer: "Imagens meramente ilustrativas. Registro de Incorporação na matrícula 158.692 do 1º RI de São José/SC."
    },
    {
        id: 6,
        slug: "terra-wave-resort",
        name: "Terrá Wave Resort",
        developer: "Paysage Corpal",
        city: "São José",
        neighborhood: "Terrá",
        state: "SC",
        address: "Rua Kiliano Hames, 1049",
        coordinates: null,
        propertyTypes: ["Terreno"],
        bedrooms: [],
        suites: [],
        areaMin: null,
        areaMax: null,
        parking: null,
        price: null,
        paymentInfo: null,
        delivery: null,
        headline: "Viva no seu próprio clube de lazer.",
        shortDescription: "Condomínio fechado com infraestrutura premium de lazer e 319 lotes no bairro que mais cresce na região.",
        description: "O Wave Resort é o primeiro condomínio do Terrá, elevando a experiência do bairro ao dia a dia de seus moradores. Uma infraestrutura premium de lazer que inclui um Boulevard de acesso, Wave Club e Wave Beach Club.",
        highlights: [
            "319 Lotes",
            "Wave Club e Beach Club",
            "Boulevard de Acesso",
            "Área verde preservada e ciclofaixas"
        ],
        amenities: [
            "Piscina com 5 ambientes",
            "Playground Aquático",
            "Raia de 25m",
            "Pool Bar",
            "Salão de Festas",
            "Playground",
            "Academia",
            "Pet Place",
            "Parrilla Gourmet",
            "Quadra de Esportes",
            "Espaço Gourmet",
            "Quadra de Beach Tennis",
            "Fitness Outdoor",
            "Portaria Imponente",
            "Espaço Mini Market"
        ],
        nearby: [
            "Bistek: 2 min",
            "BR 101: 7 min",
            "Shopping Itaguaçu: 15 min",
            "Florianópolis: 20 min"
        ],
        typologies: [],
        coverImage: "assets/images/properties/terra-wave-resort/cover.webp?v=2",
        logo: null,
        gallery: [],
        legalDisclaimer: "Imagens meramente ilustrativas. Registro de Incorporação na matrícula 158.706 do 1º RI de São José/SC."
    },
    {
        id: 7,
        slug: "residencial-becker",
        name: "Residencial Becker",
        developer: "MRV",
        city: "Blumenau",
        neighborhood: "Itoupavazinha",
        state: "SC",
        address: "Rua Prof. Jacob Ineichen, s/n",
        coordinates: null,
        propertyTypes: ["Apartamento"],
        bedrooms: [2],
        suites: [],
        areaMin: 44,
        areaMax: 44,
        parking: null,
        price: null,
        paymentInfo: null,
        delivery: null,
        headline: "Viver bem acaba de ganhar um novo significado.",
        shortDescription: "Condomínio fechado com apartamentos de 2 quartos com sacada e churrasqueira, além de lazer completo para a família.",
        description: "O Residencial Becker é o novo lar para quem busca conforto, praticidade e autonomia. Cada detalhe foi pensado para o bem-estar: condomínio fechado e lazer completo, com fácil acesso à BR-470.",
        highlights: [
            "Condomínio fechado em Blumenau",
            "Churrasqueira na sacada",
            "Financiamento facilitado (Minha Casa Minha Vida)"
        ],
        amenities: [
            "Piscinas Adulto e Infantil",
            "Quadra",
            "Playground",
            "Salão de Festas",
            "Churrasqueira",
            "Bicicletário",
            "Pet Place",
            "Espaço Gourmet"
        ],
        nearby: [
            "Supermercados (Fifolândia, Irmãos JC, Top Mix)",
            "Escolas e CEIs",
            "Acesso à BR-470"
        ],
        typologies: [
            "2 quartos (44m²)",
            "2 quartos com sacada (44m²)"
        ],
        coverImage: "assets/images/properties/residencial-becker/cover.webp?v=2",
        logo: null,
        gallery: [
            "assets/images/properties/residencial-becker/image_1.webp?v=2",
            "assets/images/properties/residencial-becker/image_2.webp?v=2",
            "assets/images/properties/residencial-becker/image_3.webp?v=2",
            "assets/images/properties/residencial-becker/image_4.webp?v=2",
            "assets/images/properties/residencial-becker/image_5.webp?v=2",
            "assets/images/properties/residencial-becker/image_6.webp?v=2",
            "assets/images/properties/residencial-becker/image_7.webp?v=2"
        ],
        legalDisclaimer: "Material exclusivamente informativo. As vendas serão realizadas somente após a obtenção do Registro de Incorporação."
    },
    {
        id: 8,
        slug: "san-george",
        name: "San George",
        developer: null,
        city: "São José",
        neighborhood: null,
        state: "SC",
        address: null,
        coordinates: null,
        propertyTypes: ["Apartamento"],
        bedrooms: [],
        suites: [],
        areaMin: null,
        areaMax: null,
        parking: null,
        price: null,
        paymentInfo: null,
        delivery: null,
        headline: "Conforto e qualidade em São José.",
        shortDescription: "Empreendimento com infraestrutura completa e excelente localização.",
        description: "O San George oferece apartamentos bem distribuídos, áreas de lazer para toda a família e a conveniência que você busca no seu dia a dia.",
        highlights: [],
        amenities: [
            "Gourmet",
            "Guarita",
            "Lazer Geral",
            "Petplace",
            "Playground",
            "Quadra"
        ],
        nearby: [],
        typologies: [],
        coverImage: "assets/images/properties/san-george/cover.webp?v=2",
        logo: null,
        gallery: [
            "assets/images/properties/san-george/image_2.webp?v=2",
            "assets/images/properties/san-george/image_3.webp?v=2",
            "assets/images/properties/san-george/image_4.webp?v=2",
            "assets/images/properties/san-george/image_5.webp?v=2",
            "assets/images/properties/san-george/image_6.webp?v=2",
            "assets/images/properties/san-george/image_7.webp?v=2"
        ],
        legalDisclaimer: null
    },
    {
        id: 9,
        slug: "the-line",
        name: "The Line",
        developer: null,
        city: "São José",
        neighborhood: null,
        state: "SC",
        address: null,
        coordinates: null,
        propertyTypes: ["Apartamento"],
        bedrooms: [],
        suites: [],
        areaMin: null,
        areaMax: null,
        parking: null,
        price: null,
        paymentInfo: null,
        delivery: null,
        headline: "Sofisticação e lazer em cada detalhe.",
        shortDescription: "Descubra o The Line, um empreendimento pensado para elevar sua qualidade de vida.",
        description: "Com uma arquitetura moderna e espaços de lazer excepcionais, o The Line proporciona experiências únicas de moradia.",
        highlights: [],
        amenities: [
            "Academia",
            "Boulevard",
            "Piscina"
        ],
        nearby: [],
        typologies: [],
        coverImage: "assets/images/properties/the-line/cover.webp?v=2",
        logo: null,
        gallery: [],
        legalDisclaimer: null
    },
    {
        id: 10,
        slug: "viva-serenita",
        name: "Viva Serenità",
        developer: null,
        city: "São José",
        neighborhood: null,
        state: "SC",
        address: null,
        coordinates: null,
        propertyTypes: ["Apartamento"],
        bedrooms: [],
        suites: [],
        areaMin: null,
        areaMax: null,
        parking: null,
        price: null,
        paymentInfo: null,
        delivery: null,
        headline: "Viva momentos inesquecíveis.",
        shortDescription: "Um empreendimento desenhado para o seu conforto e tranquilidade.",
        description: "No Viva Serenità, cada detalhe é pensado para proporcionar bem-estar. Venha conhecer e surpreenda-se.",
        highlights: [],
        amenities: [],
        nearby: [],
        typologies: [],
        coverImage: "assets/images/properties/viva-serenita/cover.webp?v=2",
        logo: null,
        gallery: [],
        legalDisclaimer: null
    }
];
