"use strict";

const properties = [
    {
        id: 1,
        slug: "scire-connect",
        name: "Scire Connect",
        developer: "Scire Empreendimentos",
        city: "São José",
        neighborhood: "Barreiros",
        state: "SC",
        address: "Rua Santo Antônio, 1093",
        coordinates: null,
        propertyTypes: ["Apartamento", "Studio"],
        bedrooms: [1, 2],
        suites: [1],
        areaMin: 32,
        areaMax: 57,
        parking: null,
        price: null,
        paymentInfo: null,
        delivery: null,
        headline: "Conecte-se com uma vida completa!",
        shortDescription: "Studios e apartamentos de 1 ou 2 dormitórios com opção de suíte, projetados especialmente para proporcionar o máximo de conforto e praticidade.",
        description: "O Scire Connect está estrategicamente localizado em Barreiros, uma das regiões mais dinâmicas e promissoras da Grande Florianópolis. Com acesso fácil a diversas conveniências, a poucos minutos do Shopping Itaguaçu e às principais vias de acesso da cidade.",
        highlights: [
            "Localização Estratégica",
            "Infraestrutura Completa",
            "Rooftop com Hidromassagem",
            "Portaria Remota"
        ],
        amenities: [
            "Rooftop",
            "Hidromassagem",
            "Fireplace",
            "Salão de Festas",
            "Academia",
            "Coworking",
            "Espaço Pizza/Parrila",
            "Cinema",
            "Sala de Jogos",
            "Pet Place",
            "Horta",
            "Playground",
            "Honest Market",
            "Ponto de Recarga VE",
            "Espaço Delivery",
            "Lavanderia OMO"
        ],
        nearby: [
            "Hospital Unimed: 1,1 km",
            "Shopping Itaguaçu: 1,3 km",
            "Fort Atacadista: 1,5 km",
            "UPA Continente: 2,2 km"
        ],
        typologies: [
            "Studio (32m²)",
            "1 dormitório (33m²)",
            "2 dormitórios (50m²)",
            "2 dormitórios com suíte (52m² a 57m²)"
        ],
        coverImage: "assets/images/properties/scire-connect/image_0.webp?v=2",
        logo: null,
        gallery: [],
        legalDisclaimer: "O presente material tem caráter exclusivamente informativo e as imagens são meramente ilustrativas."
    },
    {
        id: 2,
        slug: "scire-view",
        name: "Scire View",
        developer: "Scire Empreendimentos",
        city: "São José",
        neighborhood: "Centro Histórico",
        state: "SC",
        address: "Rua Coletor Irineu Comelli",
        coordinates: null,
        propertyTypes: ["Apartamento", "Studio"],
        bedrooms: [2, 3],
        suites: [1],
        areaMin: 32,
        areaMax: 67,
        parking: null,
        price: null,
        paymentInfo: null,
        delivery: null,
        headline: "Seu novo jeito de ver e viver São José.",
        shortDescription: "Studios e apartamentos de 2 ou 3 dormitórios, com opções de suíte, pensados para quem valoriza conforto, bem-estar e um estilo de vida mais leve.",
        description: "Com uma localização privilegiada e apartamentos com uma vista deslumbrante para o mar, o Scire View oferece uma experiência única, onde arquitetura, paisagem e qualidade de vida se encontram em perfeita harmonia.",
        highlights: [
            "Vista para o mar",
            "Arquitetura Contemporânea",
            "Plantas Inteligentes",
            "Localização Privilegiada"
        ],
        amenities: [
            "Playground",
            "Pet Place",
            "Coworking",
            "Fire Place",
            "Brinquedoteca",
            "Academia",
            "Redário",
            "Espaço Delivery",
            "Piscina Adulto e Infantil",
            "Salão Gourmet",
            "Área de Jogos Externa",
            "Salão de Festas",
            "Área de Estar",
            "Quadra de Areia",
            "Área de Piquenique",
            "Quiosque Gourmet",
            "Horta Comunitária",
            "Fitness Externo",
            "Portaria"
        ],
        nearby: [
            "Mini Mercado Bom Vizinho: 290m",
            "Farmácia São José: 620m",
            "Câmara Municipal de São José: 1,3 km",
            "Continente Shopping: 3,6 km"
        ],
        typologies: [
            "Studio (32m² a 33m²)",
            "2 dormitórios (52m²)",
            "2 dormitórios com suíte (54m² a 55m²)",
            "3 dormitórios com suíte (67m²)"
        ],
        coverImage: "assets/images/properties/scire-view/image_0.webp?v=2",
        logo: null,
        gallery: [
            "assets/images/properties/scire-view/image_0.webp?v=3",
            "assets/images/properties/scire-view/image_1.webp?v=3",
            "assets/images/properties/scire-view/image_2.webp?v=3",
            "assets/images/properties/scire-view/image_3.webp?v=3",
            "assets/images/properties/scire-view/image_4.webp?v=3",
            "assets/images/properties/scire-view/image_5.webp?v=3",
            "assets/images/properties/scire-view/image_6.webp?v=3",
            "assets/images/properties/scire-view/image_7.webp?v=3",
            "assets/images/properties/scire-view/image_8.webp?v=3",
            "assets/images/properties/scire-view/image_9.webp?v=3",
            "assets/images/properties/scire-view/image_10.webp?v=3",
            "assets/images/properties/scire-view/image_11.webp?v=3",
            "assets/images/properties/scire-view/image_12.webp?v=3",
            "assets/images/properties/scire-view/image_13.webp?v=3",
            "assets/images/properties/scire-view/image_14.webp?v=3",
            "assets/images/properties/scire-view/image_15.webp?v=3",
            "assets/images/properties/scire-view/image_16.webp?v=3",
            "assets/images/properties/scire-view/image_17.webp?v=3",
            "assets/images/properties/scire-view/image_18.webp?v=3",
            "assets/images/properties/scire-view/image_19.webp?v=3",
            "assets/images/properties/scire-view/image_20.webp?v=3",
            "assets/images/properties/scire-view/image_21.webp?v=3",
            "assets/images/properties/scire-view/image_22.webp?v=3",
            "assets/images/properties/scire-view/image_23.webp?v=3",
            "assets/images/properties/scire-view/image_24.webp?v=3",
            "assets/images/properties/scire-view/image_25.webp?v=3",
            "assets/images/properties/scire-view/image_26.webp?v=3",
            "assets/images/properties/scire-view/image_27.webp?v=3",
            "assets/images/properties/scire-view/image_28.webp?v=3",
            "assets/images/properties/scire-view/image_29.webp?v=3",
            "assets/images/properties/scire-view/image_30.webp?v=3",
            "assets/images/properties/scire-view/image_31.webp?v=3",
            "assets/images/properties/scire-view/image_32.webp?v=3",
            "assets/images/properties/scire-view/image_33.webp?v=3",
            "assets/images/properties/scire-view/image_34.webp?v=3",
            "assets/images/properties/scire-view/image_35.webp?v=3",
            "assets/images/properties/scire-view/image_36.webp?v=3",
            "assets/images/properties/scire-view/image_37.webp?v=3",
            "assets/images/properties/scire-view/image_38.webp?v=3",
            "assets/images/properties/scire-view/image_39.webp?v=3",
            "assets/images/properties/scire-view/image_40.webp?v=3",
            "assets/images/properties/scire-view/image_41.webp?v=3",
            "assets/images/properties/scire-view/image_42.webp?v=3",
            "assets/images/properties/scire-view/image_43.webp?v=3",
            "assets/images/properties/scire-view/image_44.webp?v=3",
            "assets/images/properties/scire-view/image_45.webp?v=3",
            "assets/images/properties/scire-view/image_46.webp?v=3",
            "assets/images/properties/scire-view/image_47.webp?v=3",
            "assets/images/properties/scire-view/image_48.webp?v=3",
            "assets/images/properties/scire-view/image_49.webp?v=3",
            "assets/images/properties/scire-view/image_50.webp?v=3"
        ],
        legalDisclaimer: "Material exclusivamente informativo. Imagens meramente ilustrativas."
    },
    {
        id: 3,
        slug: "scire-botanic",
        name: "Scire Botanic",
        developer: "Scire Empreendimentos",
        city: "São José",
        neighborhood: "Areias",
        state: "SC",
        address: "Rua Álvaro Medeiros de Santiago, 1630",
        coordinates: null,
        propertyTypes: ["Apartamento"],
        bedrooms: [2],
        suites: [1],
        areaMin: 47,
        areaMax: 57,
        parking: null,
        price: null,
        paymentInfo: null,
        delivery: null,
        headline: "Onde a natureza encontra o seu lar",
        shortDescription: "A proximidade com a natureza se une ao conforto de um apartamento moderno. Uma vida completa está ao seu alcance.",
        description: "No Scire Botanic, em Areias, São José, uma vida completa está ao seu alcance. A proximidade com a natureza se une ao conforto de um apartamento moderno, proporcionando a praticidade e a tranquilidade que você sempre sonhou.",
        highlights: [
            "Bosque com pista de caminhada",
            "Plantas inteligentes",
            "Fácil acesso às principais vias"
        ],
        amenities: [
            "Salão de Festas",
            "Playground",
            "Quiosques Grill",
            "Salão de Jogos",
            "Piscina",
            "Coworking",
            "Espaço Fitness",
            "Sala de Reuniões",
            "Honest Market",
            "Pet Place + Pet Care",
            "Espaço Gourmet",
            "Bosque com Pista de Caminhada",
            "Gourmet Pub",
            "Fire Place",
            "Horta",
            "Quadra",
            "Redário",
            "Fitness Externo"
        ],
        nearby: [
            "Giassi Supermercados: 1,0 km",
            "BR-101: 1,2 km",
            "Fort Atacadista: 1,6 km",
            "Shopping Itaguaçu: 6,0 km"
        ],
        typologies: [
            "2 dormitórios (47m² a 48m²)",
            "2 dormitórios demi-suítes (53m²)",
            "1 suíte + 1 dormitório (53m² a 57m²)"
        ],
        coverImage: "assets/images/properties/scire-botanic/image_1_left.webp?v=2",
        logo: null,
        gallery: [
            "assets/images/properties/scire-botanic/image_0.webp?v=3",
            "assets/images/properties/scire-botanic/image_1.webp?v=3",
            "assets/images/properties/scire-botanic/image_2.webp?v=3",
            "assets/images/properties/scire-botanic/image_3.webp?v=3",
            "assets/images/properties/scire-botanic/image_4.webp?v=3",
            "assets/images/properties/scire-botanic/image_5.webp?v=3",
            "assets/images/properties/scire-botanic/image_6.webp?v=3",
            "assets/images/properties/scire-botanic/image_7.webp?v=3",
            "assets/images/properties/scire-botanic/image_8.webp?v=3",
            "assets/images/properties/scire-botanic/image_9.webp?v=3",
            "assets/images/properties/scire-botanic/image_10.webp?v=3",
            "assets/images/properties/scire-botanic/image_11.webp?v=3",
            "assets/images/properties/scire-botanic/image_12.webp?v=3",
            "assets/images/properties/scire-botanic/image_13.webp?v=3",
            "assets/images/properties/scire-botanic/image_14.webp?v=3",
            "assets/images/properties/scire-botanic/image_15.webp?v=3",
            "assets/images/properties/scire-botanic/image_16.webp?v=3",
            "assets/images/properties/scire-botanic/image_17.webp?v=3",
            "assets/images/properties/scire-botanic/image_18.webp?v=3",
            "assets/images/properties/scire-botanic/image_19.webp?v=3",
            "assets/images/properties/scire-botanic/image_20.webp?v=3",
            "assets/images/properties/scire-botanic/image_21.webp?v=3",
            "assets/images/properties/scire-botanic/image_22.webp?v=3",
            "assets/images/properties/scire-botanic/image_23.webp?v=3",
            "assets/images/properties/scire-botanic/image_24.webp?v=3",
            "assets/images/properties/scire-botanic/image_25.webp?v=3",
            "assets/images/properties/scire-botanic/image_26.webp?v=3",
            "assets/images/properties/scire-botanic/image_27.webp?v=3"
        ],
        legalDisclaimer: null
    },
    {
        id: 5,
        slug: "terra-golden-resort",
        name: "Terrá Golden Resort",
        developer: "Paysage Corpal",
        city: "São José",
        neighborhood: "Terrá",
        state: "SC",
        address: "Rua Kiliano Hames, 1049",
        coordinates: null,
        propertyTypes: ["Terreno"],
        bedrooms: [],
        suites: [],
        areaMin: null,
        areaMax: null,
        parking: null,
        price: null,
        paymentInfo: null,
        delivery: null,
        headline: "O primeiro Condomínio Resort de terrenos.",
        shortDescription: "Eleve a sua vida no novo condomínio resort de terrenos do bairro Terrá, com acesso fácil à Ilha de Florianópolis.",
        description: "Mais que um bairro, o Terrá é a primeira urbanicidade viva de São José e Grande Florianópolis. O Terrá Golden Resort é arquitetado para proporcionar os melhores momentos, com áreas de convívio e lazer integradas.",
        highlights: [
            "Condomínio Fechado de Lotes",
            "Infraestrutura Premium de Resort",
            "Acesso fácil à BR-101"
        ],
        amenities: [
            "Piscina Adulto e Infantil",
            "Splash Kids",
            "Fitness Interno e Externo",
            "Área Beach (Quadra de Areia)",
            "Quadra Esportiva",
            "Salão de Festas & Coworking",
            "Espaço Kids Integrado",
            "Quadras de Beach Tennis"
        ],
        nearby: [],
        typologies: [],
        coverImage: "assets/images/properties/terra-golden-resort/image_104_right.webp?v=2",
        logo: null,
        gallery: [
            "assets/images/properties/terra-golden-resort/image_0.webp?v=3",
            "assets/images/properties/terra-golden-resort/image_1.webp?v=3",
            "assets/images/properties/terra-golden-resort/image_2.webp?v=3",
            "assets/images/properties/terra-golden-resort/image_3.webp?v=3",
            "assets/images/properties/terra-golden-resort/image_100.webp?v=3",
            "assets/images/properties/terra-golden-resort/image_101.webp?v=3",
            "assets/images/properties/terra-golden-resort/image_102.webp?v=3",
            "assets/images/properties/terra-golden-resort/image_103.webp?v=3",
            "assets/images/properties/terra-golden-resort/image_104.webp?v=3",
            "assets/images/properties/terra-golden-resort/image_104_right.webp?v=3",
            "assets/images/properties/terra-golden-resort/image_105.webp?v=3",
            "assets/images/properties/terra-golden-resort/image_106.webp?v=3",
            "assets/images/properties/terra-golden-resort/image_107.webp?v=3",
            "assets/images/properties/terra-golden-resort/image_108.webp?v=3",
            "assets/images/properties/terra-golden-resort/image_109.webp?v=3",
            "assets/images/properties/terra-golden-resort/image_110.webp?v=3",
            "assets/images/properties/terra-golden-resort/image_111.webp?v=3",
            "assets/images/properties/terra-golden-resort/image_112.webp?v=3",
            "assets/images/properties/terra-golden-resort/image_113.webp?v=3",
            "assets/images/properties/terra-golden-resort/image_114.webp?v=3",
            "assets/images/properties/terra-golden-resort/image_115.webp?v=3",
            "assets/images/properties/terra-golden-resort/image_116.webp?v=3",
            "assets/images/properties/terra-golden-resort/image_117.webp?v=3",
            "assets/images/properties/terra-golden-resort/image_118.webp?v=3",
            "assets/images/properties/terra-golden-resort/image_119.webp?v=3",
            "assets/images/properties/terra-golden-resort/image_120.webp?v=3",
            "assets/images/properties/terra-golden-resort/image_121.webp?v=3",
            "assets/images/properties/terra-golden-resort/image_122.webp?v=3",
            "assets/images/properties/terra-golden-resort/image_123.webp?v=3"
        ],
        legalDisclaimer: "Imagens meramente ilustrativas. Registro de Incorporação na matrícula 158.692 do 1º RI de São José/SC."
    },
    {
        id: 6,
        slug: "terra-wave-resort",
        name: "Terrá Wave Resort",
        developer: "Paysage Corpal",
        city: "São José",
        neighborhood: "Terrá",
        state: "SC",
        address: "Rua Kiliano Hames, 1049",
        coordinates: null,
        propertyTypes: ["Terreno"],
        bedrooms: [],
        suites: [],
        areaMin: null,
        areaMax: null,
        parking: null,
        price: null,
        paymentInfo: null,
        delivery: null,
        headline: "Viva no seu próprio clube de lazer.",
        shortDescription: "Condomínio fechado com infraestrutura premium de lazer e 319 lotes no bairro que mais cresce na região.",
        description: "O Wave Resort é o primeiro condomínio do Terrá, elevando a experiência do bairro ao dia a dia de seus moradores. Uma infraestrutura premium de lazer que inclui um Boulevard de acesso, Wave Club e Wave Beach Club.",
        highlights: [
            "319 Lotes",
            "Wave Club e Beach Club",
            "Boulevard de Acesso",
            "Área verde preservada e ciclofaixas"
        ],
        amenities: [
            "Piscina com 5 ambientes",
            "Playground Aquático",
            "Raia de 25m",
            "Pool Bar",
            "Salão de Festas",
            "Playground",
            "Academia",
            "Pet Place",
            "Parrilla Gourmet",
            "Quadra de Esportes",
            "Espaço Gourmet",
            "Quadra de Beach Tennis",
            "Fitness Outdoor",
            "Portaria Imponente",
            "Espaço Mini Market"
        ],
        nearby: [
            "Bistek: 2 min",
            "BR 101: 7 min",
            "Shopping Itaguaçu: 15 min",
            "Florianópolis: 20 min"
        ],
        typologies: [],
        coverImage: "assets/images/properties/terra-wave-resort/cover.webp?v=2",
        logo: null,
        gallery: [],
        legalDisclaimer: "Imagens meramente ilustrativas. Registro de Incorporação na matrícula 158.706 do 1º RI de São José/SC."
    },
    {
        id: 8,
        slug: "san-george",
        name: "San George",
        developer: null,
        city: "Blumenau",
        neighborhood: "Velha",
        state: "SC",
        address: "Rua Bruno Ruediger, s/n",
        coordinates: null,
        propertyTypes: ["Apartamento"],
        bedrooms: [],
        suites: [],
        areaMin: null,
        areaMax: null,
        parking: null,
        price: null,
        paymentInfo: null,
        delivery: null,
        headline: "Conforto e qualidade em São José.",
        shortDescription: "Empreendimento com infraestrutura completa e excelente localização.",
        description: "O San George oferece apartamentos bem distribuídos, áreas de lazer para toda a família e a conveniência que você busca no seu dia a dia.",
        highlights: [],
        amenities: [
            "Gourmet",
            "Guarita",
            "Lazer Geral",
            "Petplace",
            "Playground",
            "Quadra"
        ],
        nearby: [],
        typologies: [],
        coverImage: "assets/images/properties/san-george/image_12.webp?v=2",
        logo: null,
        gallery: [
            "assets/images/properties/san-george/image_0.webp?v=3",
            "assets/images/properties/san-george/image_1.webp?v=3",
            "assets/images/properties/san-george/image_2.webp?v=3",
            "assets/images/properties/san-george/image_3.webp?v=3",
            "assets/images/properties/san-george/image_4.webp?v=3",
            "assets/images/properties/san-george/image_5.webp?v=3",
            "assets/images/properties/san-george/image_6.webp?v=3",
            "assets/images/properties/san-george/image_7.webp?v=3",
            "assets/images/properties/san-george/image_8.webp?v=3",
            "assets/images/properties/san-george/image_9.webp?v=3",
            "assets/images/properties/san-george/image_10.webp?v=3",
            "assets/images/properties/san-george/image_11.webp?v=3",
            "assets/images/properties/san-george/image_12.webp?v=3",
            "assets/images/properties/san-george/image_13.webp?v=3",
            "assets/images/properties/san-george/image_14.webp?v=3",
            "assets/images/properties/san-george/image_15.webp?v=3",
            "assets/images/properties/san-george/image_16.webp?v=3",
            "assets/images/properties/san-george/image_17.webp?v=3"
        ],
        legalDisclaimer: null
    },
    {
        id: 9,
        slug: "the-line",
        name: "The Line",
        developer: null,
        city: "Londrina",
        neighborhood: null,
        state: "PR",
        address: null,
        coordinates: null,
        propertyTypes: ["Apartamento"],
        bedrooms: [],
        suites: [],
        areaMin: null,
        areaMax: null,
        parking: null,
        price: null,
        paymentInfo: null,
        delivery: null,
        headline: "Sofisticação e lazer em cada detalhe.",
        shortDescription: "Descubra o The Line, um empreendimento pensado para elevar sua qualidade de vida.",
        description: "Com uma arquitetura moderna e espaços de lazer excepcionais, o The Line proporciona experiências únicas de moradia.",
        highlights: [],
        amenities: [
            "Academia",
            "Boulevard",
            "Piscina"
        ],
        nearby: [],
        typologies: [],
        coverImage: "assets/images/properties/the-line/cover.webp?v=2",
        logo: null,
        gallery: [
            "assets/images/properties/the-line/image_0.webp?v=3",
            "assets/images/properties/the-line/image_1.webp?v=3",
            "assets/images/properties/the-line/image_2.webp?v=3",
            "assets/images/properties/the-line/image_100.webp?v=3",
            "assets/images/properties/the-line/image_101.webp?v=3",
            "assets/images/properties/the-line/image_102.webp?v=3",
            "assets/images/properties/the-line/image_103.webp?v=3",
            "assets/images/properties/the-line/image_104.webp?v=3",
            "assets/images/properties/the-line/image_105.webp?v=3",
            "assets/images/properties/the-line/image_106.webp?v=3",
            "assets/images/properties/the-line/image_107.webp?v=3",
            "assets/images/properties/the-line/image_108.webp?v=3",
            "assets/images/properties/the-line/image_109.webp?v=3",
            "assets/images/properties/the-line/image_110.webp?v=3",
            "assets/images/properties/the-line/image_111.webp?v=3",
            "assets/images/properties/the-line/image_112.webp?v=3",
            "assets/images/properties/the-line/image_113.webp?v=3",
            "assets/images/properties/the-line/image_114.webp?v=3",
            "assets/images/properties/the-line/image_115.webp?v=3",
            "assets/images/properties/the-line/image_116.webp?v=3",
            "assets/images/properties/the-line/image_117.webp?v=3",
            "assets/images/properties/the-line/image_118.webp?v=3",
            "assets/images/properties/the-line/image_119.webp?v=3",
            "assets/images/properties/the-line/image_120.webp?v=3",
            "assets/images/properties/the-line/image_121.webp?v=3",
            "assets/images/properties/the-line/image_122.webp?v=3",
            "assets/images/properties/the-line/image_123.webp?v=3",
            "assets/images/properties/the-line/image_124.webp?v=3",
            "assets/images/properties/the-line/image_125.webp?v=3",
            "assets/images/properties/the-line/image_126.webp?v=3",
            "assets/images/properties/the-line/image_127.webp?v=3",
            "assets/images/properties/the-line/image_128.webp?v=3",
            "assets/images/properties/the-line/image_129.webp?v=3",
            "assets/images/properties/the-line/image_130.webp?v=3",
            "assets/images/properties/the-line/image_131.webp?v=3",
            "assets/images/properties/the-line/image_132.webp?v=3",
            "assets/images/properties/the-line/image_133.webp?v=3",
            "assets/images/properties/the-line/image_134.webp?v=3",
            "assets/images/properties/the-line/image_135.webp?v=3",
            "assets/images/properties/the-line/image_136.webp?v=3",
            "assets/images/properties/the-line/image_137.webp?v=3",
            "assets/images/properties/the-line/image_138.webp?v=3",
            "assets/images/properties/the-line/image_139.webp?v=3",
            "assets/images/properties/the-line/image_140.webp?v=3",
            "assets/images/properties/the-line/image_141.webp?v=3",
            "assets/images/properties/the-line/image_142.webp?v=3",
            "assets/images/properties/the-line/image_143.webp?v=3",
            "assets/images/properties/the-line/image_144.webp?v=3",
            "assets/images/properties/the-line/image_145.webp?v=3"
        ],
        legalDisclaimer: null
    },
    {
        id: 10,
        slug: "viva-serenita",
        name: "Viva Serenità",
        developer: null,
        city: "Biguaçu",
        neighborhood: "Fundos",
        state: "SC",
        address: "Rua Homero de Miranda Gomes / Rua Júlio Teodoro Martins",
        coordinates: null,
        propertyTypes: ["Apartamento"],
        bedrooms: [],
        suites: [],
        areaMin: null,
        areaMax: null,
        parking: null,
        price: null,
        paymentInfo: null,
        delivery: null,
        headline: "Viva momentos inesquecíveis.",
        shortDescription: "Um empreendimento desenhado para o seu conforto e tranquilidade.",
        description: "No Viva Serenità, cada detalhe é pensado para proporcionar bem-estar. Venha conhecer e surpreenda-se.",
        highlights: [],
        amenities: [],
        nearby: [],
        typologies: [],
        coverImage: "assets/images/properties/viva-serenita/image_102.webp?v=2",
        logo: null,
        gallery: [
            "assets/images/properties/viva-serenita/image_0.webp?v=3",
            "assets/images/properties/viva-serenita/image_1.webp?v=3",
            "assets/images/properties/viva-serenita/image_2.webp?v=3",
            "assets/images/properties/viva-serenita/image_3.webp?v=3",
            "assets/images/properties/viva-serenita/image_4.webp?v=3",
            "assets/images/properties/viva-serenita/image_5.webp?v=3",
            "assets/images/properties/viva-serenita/image_100.webp?v=3",
            "assets/images/properties/viva-serenita/image_101.webp?v=3",
            "assets/images/properties/viva-serenita/image_102.webp?v=3",
            "assets/images/properties/viva-serenita/image_103.webp?v=3",
            "assets/images/properties/viva-serenita/image_104.webp?v=3",
            "assets/images/properties/viva-serenita/image_105.webp?v=3",
            "assets/images/properties/viva-serenita/image_106.webp?v=3",
            "assets/images/properties/viva-serenita/image_107.webp?v=3",
            "assets/images/properties/viva-serenita/image_108.webp?v=3",
            "assets/images/properties/viva-serenita/image_109.webp?v=3",
            "assets/images/properties/viva-serenita/image_110.webp?v=3",
            "assets/images/properties/viva-serenita/image_111.webp?v=3",
            "assets/images/properties/viva-serenita/image_112.webp?v=3",
            "assets/images/properties/viva-serenita/image_113.webp?v=3",
            "assets/images/properties/viva-serenita/image_114.webp?v=3",
            "assets/images/properties/viva-serenita/image_115.webp?v=3",
            "assets/images/properties/viva-serenita/image_116.webp?v=3",
            "assets/images/properties/viva-serenita/image_117.webp?v=3",
            "assets/images/properties/viva-serenita/image_118.webp?v=3",
            "assets/images/properties/viva-serenita/image_119.webp?v=3",
            "assets/images/properties/viva-serenita/image_120.webp?v=3",
            "assets/images/properties/viva-serenita/image_121.webp?v=3",
            "assets/images/properties/viva-serenita/image_122.webp?v=3",
            "assets/images/properties/viva-serenita/image_123.webp?v=3",
            "assets/images/properties/viva-serenita/image_124.webp?v=3",
            "assets/images/properties/viva-serenita/image_125.webp?v=3",
            "assets/images/properties/viva-serenita/image_126.webp?v=3",
            "assets/images/properties/viva-serenita/image_127.webp?v=3",
            "assets/images/properties/viva-serenita/image_128.webp?v=3",
            "assets/images/properties/viva-serenita/image_129.webp?v=3",
            "assets/images/properties/viva-serenita/image_130.webp?v=3",
            "assets/images/properties/viva-serenita/image_131.webp?v=3",
            "assets/images/properties/viva-serenita/image_132.webp?v=3",
            "assets/images/properties/viva-serenita/image_133.webp?v=3",
            "assets/images/properties/viva-serenita/image_134.webp?v=3",
            "assets/images/properties/viva-serenita/image_135.webp?v=3",
            "assets/images/properties/viva-serenita/image_136.webp?v=3",
            "assets/images/properties/viva-serenita/image_137.webp?v=3",
            "assets/images/properties/viva-serenita/image_138.webp?v=3",
            "assets/images/properties/viva-serenita/image_139.webp?v=3",
            "assets/images/properties/viva-serenita/image_140.webp?v=3",
            "assets/images/properties/viva-serenita/image_141.webp?v=3",
            "assets/images/properties/viva-serenita/image_142.webp?v=3",
            "assets/images/properties/viva-serenita/image_143.webp?v=3",
            "assets/images/properties/viva-serenita/image_144.webp?v=3",
            "assets/images/properties/viva-serenita/image_145.webp?v=3",
            "assets/images/properties/viva-serenita/image_146.webp?v=3",
            "assets/images/properties/viva-serenita/image_147.webp?v=3"
        ],
        legalDisclaimer: null
    },
    {
        id: 11,
        slug: "bamburgo",
        name: "Bamburgo",
        developer: "MRV",
        city: "Blumenau",
        neighborhood: null,
        state: "SC",
        address: null,
        coordinates: null,
        propertyTypes: ["Apartamento"],
        bedrooms: [],
        suites: [],
        areaMin: null,
        areaMax: null,
        parking: null,
        price: null,
        paymentInfo: null,
        delivery: null,
        headline: "Oportunidade perfeita em Blumenau.",
        shortDescription: "Torres às margens do Rio Itajaí-Açu com qualidade de vida.",
        description: "O Residencial Bamburgo é a oportunidade perfeita para quem busca morar com mais qualidade de vida em Blumenau. São torres às margens do Rio Itajaí-Açu.",
        highlights: [],
        amenities: [],
        nearby: [],
        typologies: [],
        coverImage: "assets/images/properties/bamburgo/cover.webp?v=1",
        logo: null,
        gallery: [
            "assets/images/properties/bamburgo/image_100.webp?v=3",
            "assets/images/properties/bamburgo/image_101.webp?v=3",
            "assets/images/properties/bamburgo/image_102.webp?v=3",
            "assets/images/properties/bamburgo/image_103.webp?v=3",
            "assets/images/properties/bamburgo/image_104.webp?v=3",
            "assets/images/properties/bamburgo/image_105.webp?v=3",
            "assets/images/properties/bamburgo/image_106.webp?v=3",
            "assets/images/properties/bamburgo/image_107.webp?v=3",
            "assets/images/properties/bamburgo/image_108.webp?v=3",
            "assets/images/properties/bamburgo/image_109.webp?v=3",
            "assets/images/properties/bamburgo/image_110.webp?v=3",
            "assets/images/properties/bamburgo/image_111.webp?v=3",
            "assets/images/properties/bamburgo/image_112.webp?v=3",
            "assets/images/properties/bamburgo/image_113.webp?v=3",
            "assets/images/properties/bamburgo/image_114.webp?v=3",
            "assets/images/properties/bamburgo/image_115.webp?v=3",
            "assets/images/properties/bamburgo/image_116.webp?v=3",
            "assets/images/properties/bamburgo/image_117.webp?v=3",
            "assets/images/properties/bamburgo/image_118.webp?v=3",
            "assets/images/properties/bamburgo/image_119.webp?v=3",
            "assets/images/properties/bamburgo/image_120.webp?v=3",
            "assets/images/properties/bamburgo/image_121.webp?v=3",
            "assets/images/properties/bamburgo/image_122.webp?v=3",
            "assets/images/properties/bamburgo/image_123.webp?v=3",
            "assets/images/properties/bamburgo/image_124.webp?v=3",
            "assets/images/properties/bamburgo/image_125.webp?v=3",
            "assets/images/properties/bamburgo/image_126.webp?v=3",
            "assets/images/properties/bamburgo/image_127.webp?v=3",
            "assets/images/properties/bamburgo/image_128.webp?v=3"
        ],
        legalDisclaimer: null
    },
    {
        id: 12,
        slug: "gran-malltech",
        name: "Gran Malltech",
        developer: null,
        city: "Florianópolis",
        neighborhood: "Vargem Grande",
        state: "SC",
        address: "Rua Francisco Fausto Martins, 606",
        coordinates: null,
        propertyTypes: ["Comercial"],
        bedrooms: [],
        suites: [],
        areaMin: null,
        areaMax: null,
        parking: null,
        price: null,
        paymentInfo: null,
        delivery: null,
        headline: "O seu novo polo comercial.",
        shortDescription: "Infraestrutura completa para o seu negócio crescer.",
        description: "O Gran Malltech oferece a infraestrutura e a localização ideais para impulsionar o seu negócio e garantir o sucesso da sua marca.",
        highlights: [],
        amenities: [],
        nearby: [],
        typologies: [],
        coverImage: "assets/images/properties/gran-malltech/cover.webp?v=1",
        logo: null,
        gallery: [
            "assets/images/properties/gran-malltech/image_100.webp?v=3",
            "assets/images/properties/gran-malltech/image_101.webp?v=3",
            "assets/images/properties/gran-malltech/image_102.webp?v=3",
            "assets/images/properties/gran-malltech/image_103.webp?v=3",
            "assets/images/properties/gran-malltech/image_104.webp?v=3",
            "assets/images/properties/gran-malltech/image_105.webp?v=3",
            "assets/images/properties/gran-malltech/image_106.webp?v=3",
            "assets/images/properties/gran-malltech/image_107.webp?v=3",
            "assets/images/properties/gran-malltech/image_108.webp?v=3",
            "assets/images/properties/gran-malltech/image_109.webp?v=3",
            "assets/images/properties/gran-malltech/image_110.webp?v=3",
            "assets/images/properties/gran-malltech/image_111.webp?v=3",
            "assets/images/properties/gran-malltech/image_112.webp?v=3",
            "assets/images/properties/gran-malltech/image_113.webp?v=3",
            "assets/images/properties/gran-malltech/image_114.webp?v=3",
            "assets/images/properties/gran-malltech/image_115.webp?v=3",
            "assets/images/properties/gran-malltech/image_116.webp?v=3",
            "assets/images/properties/gran-malltech/image_117.webp?v=3",
            "assets/images/properties/gran-malltech/image_118.webp?v=3",
            "assets/images/properties/gran-malltech/image_119.webp?v=3",
            "assets/images/properties/gran-malltech/image_120.webp?v=3",
            "assets/images/properties/gran-malltech/image_121.webp?v=3",
            "assets/images/properties/gran-malltech/image_122.webp?v=3",
            "assets/images/properties/gran-malltech/image_123.webp?v=3",
            "assets/images/properties/gran-malltech/image_124.webp?v=3",
            "assets/images/properties/gran-malltech/image_125.webp?v=3",
            "assets/images/properties/gran-malltech/image_126.webp?v=3",
            "assets/images/properties/gran-malltech/image_127.webp?v=3"
        ],
        legalDisclaimer: null
    },
    {
        id: 13,
        slug: "vivanti",
        name: "Palhoça Vivanti",
        developer: null,
        city: "Palhoça",
        neighborhood: "Pedra Branca",
        state: "SC",
        address: null,
        coordinates: null,
        propertyTypes: ["Apartamento"],
        bedrooms: [],
        suites: [],
        areaMin: null,
        areaMax: null,
        parking: null,
        price: null,
        paymentInfo: null,
        delivery: null,
        headline: "Uma Smart City em ascensão.",
        shortDescription: "No maior motor econômico da região, um bairro planejado para você.",
        description: "Vivanti oferece um ambiente urbano que privilegia a qualidade de vida e mobilidade urbana na Pedra Branca, Palhoça.",
        highlights: [],
        amenities: [],
        nearby: [],
        typologies: [],
        coverImage: "assets/images/properties/vivanti/cover.webp?v=1",
        logo: null,
        gallery: [
            "assets/images/properties/vivanti/image_100.webp?v=3",
            "assets/images/properties/vivanti/image_101.webp?v=3",
            "assets/images/properties/vivanti/image_102.webp?v=3",
            "assets/images/properties/vivanti/image_103.webp?v=3",
            "assets/images/properties/vivanti/image_104.webp?v=3",
            "assets/images/properties/vivanti/image_105.webp?v=3",
            "assets/images/properties/vivanti/image_106.webp?v=3",
            "assets/images/properties/vivanti/image_107.webp?v=3",
            "assets/images/properties/vivanti/image_108.webp?v=3",
            "assets/images/properties/vivanti/image_109.webp?v=3",
            "assets/images/properties/vivanti/image_110.webp?v=3",
            "assets/images/properties/vivanti/image_111.webp?v=3",
            "assets/images/properties/vivanti/image_112.webp?v=3",
            "assets/images/properties/vivanti/image_113.webp?v=3",
            "assets/images/properties/vivanti/image_114.webp?v=3",
            "assets/images/properties/vivanti/image_115.webp?v=3",
            "assets/images/properties/vivanti/image_116.webp?v=3",
            "assets/images/properties/vivanti/image_117.webp?v=3",
            "assets/images/properties/vivanti/image_118.webp?v=3",
            "assets/images/properties/vivanti/image_119.webp?v=3",
            "assets/images/properties/vivanti/image_120.webp?v=3",
            "assets/images/properties/vivanti/image_121.webp?v=3",
            "assets/images/properties/vivanti/image_122.webp?v=3",
            "assets/images/properties/vivanti/image_123.webp?v=3",
            "assets/images/properties/vivanti/image_124.webp?v=3",
            "assets/images/properties/vivanti/image_125.webp?v=3",
            "assets/images/properties/vivanti/image_126.webp?v=3",
            "assets/images/properties/vivanti/image_127.webp?v=3",
            "assets/images/properties/vivanti/image_128.webp?v=3",
            "assets/images/properties/vivanti/image_129.webp?v=3",
            "assets/images/properties/vivanti/image_130.webp?v=3",
            "assets/images/properties/vivanti/image_131.webp?v=3",
            "assets/images/properties/vivanti/image_132.webp?v=3",
            "assets/images/properties/vivanti/image_133.webp?v=3",
            "assets/images/properties/vivanti/image_134.webp?v=3",
            "assets/images/properties/vivanti/image_135.webp?v=3",
            "assets/images/properties/vivanti/image_136.webp?v=3",
            "assets/images/properties/vivanti/image_137.webp?v=3",
            "assets/images/properties/vivanti/image_138.webp?v=3",
            "assets/images/properties/vivanti/image_139.webp?v=3",
            "assets/images/properties/vivanti/image_140.webp?v=3",
            "assets/images/properties/vivanti/image_141.webp?v=3",
            "assets/images/properties/vivanti/image_142.webp?v=3",
            "assets/images/properties/vivanti/image_143.webp?v=3",
            "assets/images/properties/vivanti/image_144.webp?v=3",
            "assets/images/properties/vivanti/image_145.webp?v=3"
        ],
        legalDisclaimer: null
    },
    {
        id: 14,
        slug: "aura",
        name: "Aurora (Aura)",
        developer: null,
        city: "São José",
        neighborhood: "Serraria",
        state: "SC",
        address: "Rua Alcebíades Vidal de Souza",
        coordinates: null,
        propertyTypes: ["Apartamento"],
        bedrooms: [],
        suites: [],
        areaMin: null,
        areaMax: null,
        parking: null,
        price: null,
        paymentInfo: null,
        delivery: null,
        headline: "Seu tempo pede mais vida.",
        shortDescription: "No ritmo da sua evolução, morar bem é uma decisão estratégica.",
        description: "Aurora (Aura) não é apenas um novo endereço, é a expressão da sua próxima fase, onde a vida acontece com naturalidade.",
        highlights: [],
        amenities: [],
        nearby: [],
        typologies: [],
        coverImage: "assets/images/properties/aura/cover.webp?v=1",
        logo: null,
        gallery: [
            "assets/images/properties/aura/image_100.webp?v=3",
            "assets/images/properties/aura/image_101.webp?v=3",
            "assets/images/properties/aura/image_102.webp?v=3",
            "assets/images/properties/aura/image_103.webp?v=3",
            "assets/images/properties/aura/image_104.webp?v=3",
            "assets/images/properties/aura/image_105.webp?v=3",
            "assets/images/properties/aura/image_106.webp?v=3",
            "assets/images/properties/aura/image_107.webp?v=3",
            "assets/images/properties/aura/image_108.webp?v=3",
            "assets/images/properties/aura/image_109.webp?v=3",
            "assets/images/properties/aura/image_110.webp?v=3",
            "assets/images/properties/aura/image_111.webp?v=3",
            "assets/images/properties/aura/image_112.webp?v=3",
            "assets/images/properties/aura/image_113.webp?v=3",
            "assets/images/properties/aura/image_114.webp?v=3",
            "assets/images/properties/aura/image_115.webp?v=3",
            "assets/images/properties/aura/image_116.webp?v=3",
            "assets/images/properties/aura/image_117.webp?v=3",
            "assets/images/properties/aura/image_118.webp?v=3",
            "assets/images/properties/aura/image_119.webp?v=3",
            "assets/images/properties/aura/image_120.webp?v=3",
            "assets/images/properties/aura/image_121.webp?v=3",
            "assets/images/properties/aura/image_122.webp?v=3",
            "assets/images/properties/aura/image_123.webp?v=3",
            "assets/images/properties/aura/image_124.webp?v=3",
            "assets/images/properties/aura/image_125.webp?v=3",
            "assets/images/properties/aura/image_126.webp?v=3",
            "assets/images/properties/aura/image_127.webp?v=3",
            "assets/images/properties/aura/image_128.webp?v=3",
            "assets/images/properties/aura/image_129.webp?v=3",
            "assets/images/properties/aura/image_130.webp?v=3",
            "assets/images/properties/aura/image_131.webp?v=3",
            "assets/images/properties/aura/image_132.webp?v=3",
            "assets/images/properties/aura/image_133.webp?v=3",
            "assets/images/properties/aura/image_134.webp?v=3",
            "assets/images/properties/aura/image_135.webp?v=3",
            "assets/images/properties/aura/image_136.webp?v=3",
            "assets/images/properties/aura/image_137.webp?v=3",
            "assets/images/properties/aura/image_138.webp?v=3",
            "assets/images/properties/aura/image_139.webp?v=3",
            "assets/images/properties/aura/image_140.webp?v=3",
            "assets/images/properties/aura/image_141.webp?v=3",
            "assets/images/properties/aura/image_142.webp?v=3",
            "assets/images/properties/aura/image_143.webp?v=3",
            "assets/images/properties/aura/image_144.webp?v=3",
            "assets/images/properties/aura/image_145.webp?v=3",
            "assets/images/properties/aura/image_146.webp?v=3",
            "assets/images/properties/aura/image_147.webp?v=3",
            "assets/images/properties/aura/image_148.webp?v=3",
            "assets/images/properties/aura/image_149.webp?v=3",
            "assets/images/properties/aura/image_150.webp?v=3",
            "assets/images/properties/aura/image_151.webp?v=3",
            "assets/images/properties/aura/image_152.webp?v=3",
            "assets/images/properties/aura/image_153.webp?v=3",
            "assets/images/properties/aura/image_154.webp?v=3",
            "assets/images/properties/aura/image_155.webp?v=3",
            "assets/images/properties/aura/image_156.webp?v=3",
            "assets/images/properties/aura/image_157.webp?v=3",
            "assets/images/properties/aura/image_158.webp?v=3",
            "assets/images/properties/aura/image_159.webp?v=3",
            "assets/images/properties/aura/image_160.webp?v=3",
            "assets/images/properties/aura/image_161.webp?v=3",
            "assets/images/properties/aura/image_162.webp?v=3",
            "assets/images/properties/aura/image_163.webp?v=3",
            "assets/images/properties/aura/image_164.webp?v=3",
            "assets/images/properties/aura/image_165.webp?v=3",
            "assets/images/properties/aura/image_166.webp?v=3",
            "assets/images/properties/aura/image_167.webp?v=3",
            "assets/images/properties/aura/image_168.webp?v=3"
        ],
        legalDisclaimer: null
    }
];