import re
with open(r'c:\REP-ANTIGRAVITY\js\properties.js', 'r', encoding='utf-8') as f:
    content = f.read()

new_props = '''    {
        id: 11,
        slug: "bamburgo",
        name: "Bamburgo",
        developer: "MRV",
        city: "Blumenau",
        neighborhood: null,
        state: "SC",
        address: null,
        coordinates: null,
        propertyTypes: ["Apartamento"],
        bedrooms: [],
        suites: [],
        areaMin: null,
        areaMax: null,
        parking: null,
        price: null,
        paymentInfo: null,
        delivery: null,
        headline: "Oportunidade perfeita em Blumenau.",
        shortDescription: "Torres às margens do Rio Itajaí-Açu com qualidade de vida.",
        description: "O Residencial Bamburgo é a oportunidade perfeita para quem busca morar com mais qualidade de vida em Blumenau. São torres às margens do Rio Itajaí-Açu.",
        highlights: [],
        amenities: [],
        nearby: [],
        typologies: [],
        coverImage: "assets/images/properties/bamburgo/cover.webp?v=1",
        logo: null,
        gallery: [],
        legalDisclaimer: null
    },
    {
        id: 12,
        slug: "gran-malltech",
        name: "Gran Malltech",
        developer: null,
        city: "",
        neighborhood: null,
        state: "",
        address: null,
        coordinates: null,
        propertyTypes: ["Comercial"],
        bedrooms: [],
        suites: [],
        areaMin: null,
        areaMax: null,
        parking: null,
        price: null,
        paymentInfo: null,
        delivery: null,
        headline: "O seu novo polo comercial.",
        shortDescription: "Infraestrutura completa para o seu negócio crescer.",
        description: "O Gran Malltech oferece a infraestrutura e a localização ideais para impulsionar o seu negócio e garantir o sucesso da sua marca.",
        highlights: [],
        amenities: [],
        nearby: [],
        typologies: [],
        coverImage: "assets/images/properties/gran-malltech/cover.webp?v=1",
        logo: null,
        gallery: [],
        legalDisclaimer: null
    },
    {
        id: 13,
        slug: "vivanti",
        name: "Palhoça Vivanti",
        developer: null,
        city: "Palhoça",
        neighborhood: "Pedra Branca",
        state: "SC",
        address: null,
        coordinates: null,
        propertyTypes: ["Apartamento"],
        bedrooms: [],
        suites: [],
        areaMin: null,
        areaMax: null,
        parking: null,
        price: null,
        paymentInfo: null,
        delivery: null,
        headline: "Uma Smart City em ascensão.",
        shortDescription: "No maior motor econômico da região, um bairro planejado para você.",
        description: "Vivanti oferece um ambiente urbano que privilegia a qualidade de vida e mobilidade urbana na Pedra Branca, Palhoça.",
        highlights: [],
        amenities: [],
        nearby: [],
        typologies: [],
        coverImage: "assets/images/properties/vivanti/cover.webp?v=1",
        logo: null,
        gallery: [],
        legalDisclaimer: null
    },
    {
        id: 14,
        slug: "aura",
        name: "Aurora (Aura)",
        developer: null,
        city: "",
        neighborhood: null,
        state: "",
        address: null,
        coordinates: null,
        propertyTypes: ["Apartamento"],
        bedrooms: [],
        suites: [],
        areaMin: null,
        areaMax: null,
        parking: null,
        price: null,
        paymentInfo: null,
        delivery: null,
        headline: "Seu tempo pede mais vida.",
        shortDescription: "No ritmo da sua evolução, morar bem é uma decisão estratégica.",
        description: "Aurora (Aura) não é apenas um novo endereço, é a expressão da sua próxima fase, onde a vida acontece com naturalidade.",
        highlights: [],
        amenities: [],
        nearby: [],
        typologies: [],
        coverImage: "assets/images/properties/aura/cover.webp?v=1",
        logo: null,
        gallery: [],
        legalDisclaimer: null
    }
];'''

content = re.sub(r'\n\];\s*$', ',\n' + new_props, content)
with open(r'c:\REP-ANTIGRAVITY\js\properties.js', 'w', encoding='utf-8') as f:
    f.write(content)
print('Updated properties.js successfully')
